config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "items#index"
  resources :items do
    resources :comments, only: :create
    resources :likes, only: [:index, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :text, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes

  validates :title, presence: true
  validates :concept, presence: true
  validates :feature, presence: true

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: true
  validates :birthday, presence: true

  has_many :items
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @comment = @item.comments.new(comment_params)
    if @comment.save
      redirect_to item_path(@item)
    else
      @comments = @item.comments.includes(:user)
      redirect_to item_path(@item)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :item_action, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user_access, only: [:new, :creste, :edit, :update, :destroy]
  before_action :log_edit, only: [:edit, :update, :destroy]

  def index
    @items = Item.all
    @item = @items.first
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path
  end
  private

  def item_action
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :concept, :feature, :merit, :demerit).merge(user_id: current_user.id)
  end

  def check_user_access
    unless current_user == User.find_by(nickname: 'owner')
      redirect_to root_path, alert: "アクセス権限がありません。"
    end
  end

  def log_edit
    redirect_to root_path unless current_user == @item.user 
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item

  def index
    @likes = current_user.likes
  end

  def create
    like = current_user.likes.build(item_id: params[:item_id], user_id: current_user.id)
    like.save
    render 'create.js.erb'
  end


  def destroy
    like = Like.find_by(item_id: params[:item_id], user_id: current_user.id)
    like.destroy
    render 'destroy.js.erb'
  end

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/items/edit.html.erb
<%= render "shared/second-header" %>

<div class="main">
  <div class="items-main">
    <h2 class="items-title">保険の内容を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

      <div class="field">
        <%= f.label :title, "保険名" %><br />
        <%= f.text_field :title, class: :form_title, id:"insurance_title" %>
      </div>

      <div class="field">
        <%= f.label :concept, "解説" %><br />
        <%= f.text_area :concept, class: :form_text, id:"concept" %>
      </div>

      <div class="field">
        <%= f.label :feature, "特徴" %><br />
        <%= f.text_area :feature, class: :form_text, id:"feature" %>
      </div>

      <div class="field">
        <%= f.label :merit, "メリット" %><br />
        <%= f.text_area :merit, class: :form_text, id:"merit" %>
      </div>

      <div class="field">
        <%= f.label :demerit, "デメリット" %><br />
        <%= f.text_area :demerit, class: :form_text, id:"demerit" %>
      </div>

      <div class="actions-edit">
        <%= f.submit "編集する", class: :form_btn  %>
      </div>
      <div class="back-btn">
        <%=link_to 'もどる', item_path, class:"form_btn" %>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class='first-view'>
    <!--「トップ画像」を表示する-->
    <%= image_tag "toptitle.png", class:"top-image" %>
    <!--画像内に見出しの表示-->
    <div class='title-contents'>
      <h2 class='service-title'>
        ライフスタイルに合った保険選び
      </h2>
      <p class='service-subtitle'>
        安心した毎日の暮らしへ
      </p>
      <p class='service-subtitle'>
        保険を知る第一歩。
      </p>
    </div>
  </div>

  <%# サイト概要の説明 %>
  <div class='select-main'>
    <div class='select-contents'>
      <h3 class='select-title'>
        Message
      </h3>
      <p class='select-text'>
        どのような保険があるのかわからない、他の人はどこの保険に加入しているのだろう？
        といった保険の悩みを解決します。<br>
        一般的な保険の種類や内容の解説を記載しております。また各保険分野において様々な人とコメントにて相談をすることができ,
        安心した人生設計へのお手伝いをいたします。
      </p>
    </div>
    <%# %保険とは解説 %>
    <div class='select-contents'>
      <h3 class='select-title'>
        保険とは
      </h3>
      <p class='select-text'>
        何気ない毎日、平和な日常はあたりまえにあるのではありません。<br>
        家族の誰かが不運にも急な事故や病気によって、死亡してしまったら？高額な治療費が必要となったら？
        人生におけるこのようなリスクは誰に対しても起こりうる可能性があります。<br>
        その万一の状況が起きてしまった時に自分たちだけの力で乗り越えられる人はなかなか多くありません。
        その場合に自分や家族を守るのは保険です。<br>
        また災害や将来の資産設計そのような心配事に備えることができるのも保険です。
        自分や家族を守るために保険について理解を深めていきましょう。
      </p>
    </div>
  </div>

  <div class='welcom-nickname'>
    <% if user_signed_in? %>
    <p class='nickaname-view'>ようこそ <%= current_user.nickname %> さん</p>
    <% end %>
  </div>

  <%# 保険一覧 %>
  <div class='item-contents'>
    <h3 class='select-insurance'>
      保険一覧
    </h3>
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='item-list'>
          <div class='item-info'>
            <div class='item-sub'>
              <%= link_to item.title, item_path(item.id), class: :item_none %>
            </div>
          </div>
          <div class='item-feature'>
            <%= link_to item.concept, item_path(item.id), class: :item_none %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<% if current_user == User.find_by(nickname: 'owner') %>
  <%= link_to "新規投稿", new_item_path, class: "purchase-btn" %>
<% end %>
<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render "shared/second-header" %>

<div class="main">
  <div class="items-main">
    <h2 class="items-title">保険の内容を入力</h2>
    <%= form_with model: @item, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      
      <div class="field">
        <%= f.label :title, "保険名" %><br />
        <%= f.text_field :title, class: :form_title, id:"insurance_title" %>
      </div>

      <div class="field">
        <%= f.label :concept, "解説" %><br />
        <%= f.text_area :concept, class: :form_text, id:"concept" %>
      </div>

      <div class="field">
        <%= f.label :feature, "特徴" %><br />
        <%= f.text_area :feature, class: :form_text, id:"feature" %>
      </div>

      <div class="field">
        <%= f.label :merit, "メリット (任意)" %><br />
        <%= f.text_area :merit, class: :form_text, id:"merit" %>
      </div>

      <div class="field">
        <%= f.label :demerit, "デメリット (任意)" %><br />
        <%= f.text_area :demerit, class: :form_text, id:"demerit" %>
      </div>

      <div class="actions">
        <%= f.submit "投稿する", class: :form_btn  %>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.title %>
    </h2>
    <% if user_signed_in? %>
      <% if current_user.id == @item.user_id %>
        <div class="item-edit">
          <%= link_to "編集", edit_item_path, method: :get, class:"purchase-btn-red" %>
          <%= link_to "削除", item_path, method: :delete, class:"purchase-btn-red" %>
        </div>
      <% end %>
      <div id="like-btn<%= @item.id %>">
        <%= render partial: "likes/like", locals: { item: @item } %>
      </div>
    <% end %>
  </div>
  <div class="item-page">
    <div class="item-show">
      <p class="content-list">説明</p>
      <p class="item-detail">
      <%= @item.concept %>
      </p>
    </div>
    <div class="item-show">
      <p class="content-list">特徴</p>
      <p class="item-detail">
      <%= @item.feature %>
      </p>
    </div>
    <div class="item-show">
      <p class="content-list">メリット</p>
      <p class="item-detail">
      <%= @item.merit %>
      </p>
    </div>
    <div class="item-show">
      <p class="content-list">デメリット</p>
      <p class="item-detail">
      <%= @item.demerit %>
      </p>
    </div>
  </div>
  <div class='comment-form'>
    <div class='comment-show'>
      <h4 class='comment-title'>チャットフォーム</h4>
      <% @comments.each do |comment| %>
        <div class='comment-text'>
          <p><%= comment.user.nickname %> : <%= comment.text %></p>
        </div>
      <% end %>
    </div>
    <div class='container'>
      <% if user_signed_in? %>
        <%= form_with(model: [@item, @comment], class: 'form', local: true) do |f| %>
        <div class='message-content'>
          <%= f.text_area :text, class: 'form-message', placeholder: "コメントする", rows: "2" %>
        </div>
        <div class='message-send'>
          <%= f.submit "SEND", class: 'form-submit' %>
        </div>
        <% end %>
      <% else %>
        <div class='comment-note'>
          ※チャット機能を利用するにはアカウントへログインしてください※
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insurance</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if @item.liked_by?(current_user)%>
  <%=link_to "お気に入り解除", item_like_path(@item, @item.likes.find_by(user_id: current_user.id)),  method: :delete, class: "item_likes" , remote: true %>
<% else %>
  <%=link_to "お気に入り登録", item_likes_path(@item), method: :post, class: "item_likes" , remote: true %>
<% end %>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"

app/views/likes/index.html.erb
<%= render "shared/second-header" %>
<div class='item-contents'>
  <p class='user-mypage'><%= current_user.nickname %> さんのお気に入り一覧</p>
  <ul class='item-lists'>
    <% @likes.each do |like| %>
      <li class='item-list'>
        <div class='item-info'>
          <div class='item-sub'>
            <%= link_to like.item.title, item_path(like.item.id), class: :item_none %>
          </div>
        </div>
        <div class='item-feature'>
          <%= link_to like.item.concept, item_path(like.item.id), class: :item_none %>
        </div>
      </li>
    <% end %>
    <% if @likes.empty? %>
      <h3 class='likes-message'>
        お気に入りの登録がされていません<br>
        お気に入り登録内容は登録後に反映されます
      </h3>
    <% end %>
  </ul>
</div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p class="copyright">Copyright © Life Planner All rights reserved.</p>
</footer>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <div class="heading">
    <div class="inner">
      <div class="nav__left">
        <%= link_to "Life Planner", root_path, class: "title" %>
      </div>
      <div class="user_nav">
        <ul class="user_info">
          <% if user_signed_in? %>
            <li>
              <%= link_to "マイページ", item_likes_path(item_id: @item.id, user_id: current_user.id), class: "post" %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" %>
            </li>
          <% else %>
            <li>
              <%= link_to 'ログイン', new_user_session_path, class: "post" %>
              <%= link_to '新規登録', new_user_registration_path, class: "post" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class="top-page-header">
  <div class="heading">
    <div class="inner">
      <div class="nav__left">
        <%= link_to "Life Planner", root_path, class: "title" %>
      </div>
    </div>
  </div>
</header>